spring:
  application:
    name: sistemas_avaliacao
  datasource:
    url: jdbc:mariadb://localhost:3307/sistemas_avaliacao
    username: usuario
    password: senha
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: seu email
    password: sua senha gerada
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: sua_secret
  expiration: 86400000